version: '3.4'

volumes:
  api:

services:
  gw:
    image: jrgensen/gateway
    platform: linux/x86_64
    environment:
      PROXY_MAPPINGS: >
        mobilepay:api
        sql:phpmyadmin
    ports:
    - 80

  api:
    build:
      context: .
      target: dev
      dockerfile: docker/Dockerfile
    environment:
      #GO_BUILD_FLAGS: -race
      STAN_DSN: stan://dev.nathejk.dk:4222/nathejk
      DB_DSN: bruger:kodeord@tcp(db:3306)/tilmelding?parseTime=true
      REPORT_API_KEY: ABC123
    volumes:
    - .:/app
    - api:/go
    depends_on:
    - gw
    - db

  db:
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: ib
      MYSQL_DATABASE: tilmelding
      MYSQL_USER: bruger
      MYSQL_PASSWORD: kodeord
      TZ: Europe/Copenhagen

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ib
      PMA_USER: bruger
      PMA_PASSWORD: kodeord
    depends_on:
    - gw
    - db

